# Generated by Django 2.1.3 on 2018-12-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='opp',
            field=models.CharField(default='Momochi', max_length=10),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='player',
            field=models.CharField(default='Tokido', max_length=10),
        ),
    ]
