# Generated by Django 2.1.3 on 2018-12-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soup',
        ),
    ]
