# Generated by Django 2.1.3 on 2018-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_delete_soup'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tag',
            field=models.CharField(default='body', max_length=7),
        ),
    ]
