# Generated by Django 2.1.3 on 2018-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20181210_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='tag',
            new_name='main_tag',
        ),
        migrations.AddField(
            model_name='url',
            name='sub_tag',
            field=models.CharField(default='a', max_length=7),
        ),
    ]
